version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gvgroup_order_management
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: gvgroup_order_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: