spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://user-management-app:8081

  datasource:
    url: jdbc:postgresql://postgres:5433/gvgroup_order_management
    username: user
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialec
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      group-id: order_management_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    bootstrap-servers: kafka:29092


server:
  servlet:
    context-path: /api